name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client rsync
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_KEY }}" > private_key
          chmod 600 private_key
          ssh-keyscan -t rsa ${{ secrets.DEPLOYMENT_HOST }} > ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add private_key
          cp .env.dist .env
          cd frontend
          yarn install
          yarn generate:admin
          yarn build:site
          cd ..

      - name: Deploy to server
        env:
          DEPLOYMENT_USER: ${{ secrets.DEPLOYMENT_USER }}
          DEPLOYMENT_HOST: ${{ secrets.DEPLOYMENT_HOST }}
          FRONTEND_PATH: ${{ secrets.FRONTEND_PATH }}
          WWW_PATH: ${{ secrets.WWW_PATH }}
          CORE_PATH: ${{ secrets.CORE_PATH }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
        run: |
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "mkdir -p $WWW_PATH"
          rsync -r --del --force --exclude 'node_modules' --stats -e "ssh -i private_key" frontend/ $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$FRONTEND_PATH
          rsync -r --del --force -e "ssh -i private_key" www/ $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$WWW_PATH
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "mkdir -p $CORE_PATH"
          rsync -r --del --force --exclude 'vendor' --stats -e "ssh -i private_key" core/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$CORE_PATH
          rsync -r --del --force -e "ssh -i private_key" composer.* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$BASE_PATH
          #ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $BASE_PATH && ~/bin/php ~/bin/composer install --no-dev"
          #ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $CORE_PATH && ~/bin/php ./vendor/bin/phinx migrate"
          #ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $FRONTEND_PATH && ~/bin/yarn --ignore-engines && ~/bin/yarn restart"
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $BASE_PATH && /usr/bin/php /usr/local/bin/composer update"
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $BASE_PATH && /usr/bin/php /usr/local/bin/composer install --no-dev"
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $CORE_PATH && /usr/bin/php ./vendor/bin/phinx migrate"
          ssh -i private_key $DEPLOYMENT_USER@$DEPLOYMENT_HOST "cd $FRONTEND_PATH && /root/.nvm/versions/node/v16.10.0/bin/yarn --ignore-engines && /root/.nvm/versions/node/v16.10.0/bin/yarn restart"
